version: '3'

services:

  api:
    container_name: backend
    image: snoweegamecorp
    build: .
    working_dir: /java-app
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./java-app:/java-app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    networks:
      - snoweenet
    restart: always
    
networks:
  snoweenet:
    driver: bridge
