pipeline{
    agent any

	environment {
		PASS = credentials('dockerhub-pass')
	}

    stages {
        stage('Build') {
            steps {
            sh '''
                ./local/scripts/build/mvn.sh mvn clean package -DskipTests
            '''
            }
            post {
                success {
                    archiveArtifacts artifacts: 'local/java-app/target/*.jar', fingerprint: true
                }
            }
        }
        stage('Clean-UP') {
                steps {
                    sh './local/scripts/clean/clean_dump.sh'
                }
        }
        stage('Start-Deploy') {
            steps {
                build job: "Deploy-Backend", wait: true
            }
        }
    }
}