version: '3'

services:

  database:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "snowee"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - snoweenet
    restart: always

  api:
    container_name: backend
    build: .
    working_dir: /java-app
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./java-app:/java-app
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - database
    depends_on:
      - database
    networks:
      - snoweenet
    restart: always
    
networks:
  snoweenet:
    driver: bridge
