version: '3'

services:

  database:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "snowee"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - snoweenet
    restart: always

  backend:
    container_name: snowee-api
    image: ericknbaraujo/snoweegamecorp:latest
    ports:
      - "9000:8080"
    links:
      - database
    depends_on:
      - database
    networks:
      - snoweenet
    restart: always
    
networks:
  snoweenet:
    driver: bridge
