#Banco Postgres

app:
  message: This is the property file to the ${spring.application.name} specific for PROD environment

spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
