#Banco Postgres

app:
  message: This is the property file to the ${spring.application.name} specific for PROD environment

spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: true

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:snoweeapi}
      client-secret: ${CLIENT_SECRET:snoweeapi}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}