#Banco H2

app:
  message: This is the property file to the ${spring.application.name} specific for DEV environment

spring:
  datasource:
    url: jdbc:h2:mem:dbsnowee;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:${env.client.id}}
      client-secret: ${CLIENT_SECRET:${env.client.secret}}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:1800}