#Banco Postgres

app:
  message: This is the property file to the ${spring.application.name} specific for PROD environment

server:
   port: 8080
   ssl:
      enabled: true
      keyStoreType: PKCS12
      key-store: snoweeapi.p12
      key-store-password: ${env.keystore.password}

spring:
  hikari:
    connection-test-query: SELECT 1
    minimum-idle: 1
    maximum-pool-size: 10
    pool-name: snowee-database
    auto-commit: FALSE
    connection-timeout: 30000
  datasource:
    url: jdbc:postgresql://${env.database.hostname}:5432/dbsnowee
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: snowee
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: true

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:${env.client.id}}
      client-secret: ${CLIENT_SECRET:${env.client.secret}}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}

