INSERT INTO tb_themes (ID, NAME) VALUES (1,'Angular')
INSERT INTO tb_themes (ID, NAME) VALUES (2,'Bash')
INSERT INTO tb_themes (ID, NAME) VALUES (3,'Docker')
INSERT INTO tb_themes (ID, NAME) VALUES (4,'Heroku')
INSERT INTO tb_themes (ID, NAME) VALUES (5,'Java')
INSERT INTO tb_themes (ID, NAME) VALUES (6,'Jenkins')
INSERT INTO tb_themes (ID, NAME) VALUES (7,'Maven')
INSERT INTO tb_themes (ID, NAME) VALUES (8,'Selenium')
INSERT INTO tb_themes (ID, NAME) VALUES (9,'Spring Boot')